

name: '[DEV Manual] Deploy explorer frontend'

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:
      branch:
        description: 'Branch to deploy on dev'
        required: true  # Makes the branch input mandatory
        default: 'dev'

jobs:
  dev_deploy_explorer_frontend:
    uses: ./.github/workflows/dev-frontend.yml
    with:
      SWR_ORGANIZATION: dev-qubetics
      ARGOCD_BRANCH: dev
      HUAWEI_REGION: 'ap-southeast-3'
      ARGOCD_REPOSITORY: Qubetics/argocd-qubetics
      DEPLOYMENT_PATH: Frontend/deployment.yaml
      HUAWEI_IMAGE: dev-explorer-frontend
      DOCKER_USERNAME: ap-southeast-3@BQG9INQF0BKVHSNQOLJG
      ENV: ${{ vars.DEV_ENV }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GIT_SSH_KEY: ${{ secrets.ARGOCD_SSH_KEY }}
